# Generated by Django 3.1.6 on 2021-03-14 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('home_loc', models.CharField(choices=[('IN', 'INDIANA'), ('KY', 'KENTUCKY')], max_length=2)),
                ('work_loc', models.CharField(choices=[('IN', 'INDIANA'), ('KY', 'KENTUCKY')], max_length=2)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('vac_group', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('notify', models.BooleanField()),
                ('is_notified', models.BooleanField()),
            ],
        ),
    ]
