# Generated by Django 3.1.6 on 2021-03-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='home_loc',
            new_name='home_state',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='vac_group',
            new_name='vaccine_group',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='work_loc',
            new_name='work_state',
        ),
    ]
