# Generated by Django 3.1.6 on 2021-04-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210313_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
