# Generated by Django 3.1.6 on 2021-04-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210401_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_notified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='essential',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='vaccine_group',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('u', 'Unknown')], max_length=1),
        ),
    ]
