# Generated by Django 3.1.6 on 2021-04-12 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210401_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_state_text', models.CharField(max_length=200)),
                ('work_state_text', models.CharField(max_length=200)),
                ('age_text', models.IntegerField(default=0)),
                ('essential_text', models.CharField(max_length=200)),
                ('vaccine_group_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
