from django.test import TestCase

# Create your tests here.
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestIntrotests():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_nav1(self):
        # Test name: nav1
        # Step # | name | target | value
        # 1 | open | /home |
        self.driver.get("http://127.0.0.1:8000/home")
        # 2 | setWindowSize | 854x700 |
        self.driver.set_window_size(854, 700)
        # 3 | click | linkText=Am I eligible? |
        self.driver.find_element(By.LINK_TEXT, "Am I eligible?").click()
        # 4 | open | /create |
        self.driver.get("http://127.0.0.1:8000/create")

    def test_create1(self):
        # Test name: create1
        # Step # | name | target | value
        # 1 | open | /create/ |
        self.driver.get("http://127.0.0.1:8000/create/")
        # 2 | setWindowSize | 854x700 |
        self.driver.set_window_size(854, 700)
        # 3 | click | id=id_home_state |
        self.driver.find_element(By.ID, "id_home_state").click()
        # 4 | select | id=id_home_state | label=INDIANA
        dropdown = self.driver.find_element(By.ID, "id_home_state")
        dropdown.find_element(By.XPATH, "//option[. = 'INDIANA']").click()
        # 5 | click | css=#id_home_state > option:nth-child(2) |
        self.driver.find_element(By.CSS_SELECTOR, "#id_home_state > option:nth-child(2)").click()
        # 6 | click | id=id_work_state |
        self.driver.find_element(By.ID, "id_work_state").click()
        # 7 | select | id=id_work_state | label=KENTUCKY
        dropdown = self.driver.find_element(By.ID, "id_work_state")
        dropdown.find_element(By.XPATH, "//option[. = 'KENTUCKY']").click()
        # 8 | click | css=#id_work_state > option:nth-child(3) |
        self.driver.find_element(By.CSS_SELECTOR, "#id_work_state > option:nth-child(3)").click()
        # 9 | type | id=id_age | 26
        self.driver.find_element(By.ID, "id_age").send_keys("26")
        # 10 | click | id=id_age |
        self.driver.find_element(By.ID, "id_age").click()
        # 11 | click | id=id_vaccine_group |
        self.driver.find_element(By.ID, "id_vaccine_group").click()
        # 12 | select | id=id_vaccine_group | label=D
        dropdown = self.driver.find_element(By.ID, "id_vaccine_group")
        dropdown.find_element(By.XPATH, "//option[. = 'D']").click()
        # 13 | click | css=option:nth-child(5) |
        self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(5)").click()

